trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'azure-terraform-sc'

stages:

# 1. Terraform Init + Validate
- stage: Terraform_Init_Validate
  displayName: 'Terraform Init and Validate'
  jobs:
  - job: Init_Validate
    steps:

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      displayName: 'Terraform Init and Validate'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform
          terraform init
          terraform validate


# 2. Terraform Plan
- stage: Terraform_Plan
  displayName: 'Terraform Plan'
  dependsOn: Terraform_Init_Validate
  jobs:
  - job: Plan
    steps:

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      displayName: 'Terraform Plan'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform
          terraform init
          terraform plan


# 3. Terraform Apply
- stage: Terraform_Apply
  displayName: 'Terraform Apply'
  dependsOn: Terraform_Plan
  jobs:
  - job: Apply
    steps:

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      displayName: 'Terraform Apply'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform
          terraform init
          terraform apply -auto-approve


# 4. Terraform Destroy
- stage: Terraform_Destroy
  displayName: 'Terraform Destroy'
  dependsOn: Terraform_Apply
  jobs:
  - job: Destroy
    steps:

    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      displayName: 'Terraform Destroy'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd terraform
          terraform init
          terraform destroy -auto-approve
